# Generated by Django 2.2 on 2020-12-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201207_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='dimension',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
